version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:5000"
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - FLASK_ENV=production
    command: gunicorn --bind 0.0.0.0:5000 app:app